#!/usr/bin/env python3
"""Design-based uncertainty for the frozen, five-run LLM evaluation.

Consumes portable matrices from 24_prepare_sampling_uncertainty.py. Does not
load models, contact APIs, or draw another benchmark subset.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from amlc import paths
from amlc.analysis.sampling_uncertainty import summarize_cell, summarize_contrast


def _interval_tex(bounds, scale=1.0, digits=4):
    """Round endpoints outwards so displayed intervals do not shrink."""
    factor = 10 ** digits
    lo = math.floor(float(bounds[0]) * scale * factor) / factor
    hi = math.ceil(float(bounds[1]) * scale * factor) / factor
    return f"$[{lo:.{digits}f}, {hi:.{digits}f}]$"


def _model_tex(name):
    return name.replace("Nemotron-3-Nano", "Nem-Nano").replace(
        "Nemotron-3-Super", "Nem-Super").replace("397B-A17B", "397B")


def write_paper_tables(out, cells, contrasts):
    out.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Generated by scripts/25_score_sampling_uncertainty.py; do not edit values.",
        r"\begin{table*}[t]", r"\centering", r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{llrrrlrl}", r"\toprule",
        r"Model & M & $F1_{\rm HT}$ & $\mathrm{SD}_{\rm run}$ & $\mathrm{SE}_{\rm samp}$ & 95\% interval & Lift & 95\% interval \\",
        r" & & (\%) & ($10^{-3}$ pp) & ($10^{-3}$ pp) & (\%) & & \\",
        r"\midrule",
    ]
    for dataset in ("HI-Small", "LI-Small"):
        lines.append(r"\multicolumn{8}{c}{\textit{" + dataset + r"}} \\")
        for row in cells:
            if row["dataset"] != dataset:
                continue
            r = row["statistics"]
            lines.append(
                f"{_model_tex(row['model'])} & {row['prompting'][-2:]} & "
                f"{100*r['mean']['f1']:.4f} & {1e5*r['seed_sd']['f1']:.2f} & "
                f"{1e5*r['sampling_se']['f1']:.2f} & "
                f"{_interval_tex(r['envelope95']['f1'], 100)} & "
                f"{r['mean']['lift']:.3f} & {_interval_tex(r['envelope95']['lift'], digits=4)} \\\\"
            )
        lines.append(r"\midrule" if dataset == "HI-Small" else r"\bottomrule")
    lines.extend([
        r"\end{tabular}",
        (r"\caption{Sampling uncertainty for the 28 five-run mean LLM results. "
        r"F1 and its interval endpoints are percentages; run SD and linearized "
        r"sampling SE are in $10^{-3}$ percentage points. Lift is precision divided "
        r"by full-test illicit prevalence. Intervals are conservative, cellwise "
        r"95\% confidence envelopes obtained from simultaneous hypergeometric "
        r"bounds for 15 run--stratum counts (\Cref{app:estimation}). They condition "
        r"on the frozen design, realized allocation, and five fixed prediction "
        r"vectors; they do not include uncertainty over future inference runs. "
        r"Coverage is not simultaneous across the 28 cells. Endpoints are rounded outwards.}"),
        r"\label{tab:llm_sampling_uncertainty}", r"\end{table*}", "",
    ])
    (out / "llm_sampling_uncertainty.tex").write_text("\n".join(lines))

    lines = [
        "% Generated by scripts/25_score_sampling_uncertainty.py; do not edit values.",
        r"\begin{table*}[t]", r"\centering", r"\small",
        r"\setlength{\tabcolsep}{5pt}", r"\begin{tabular}{llrrlrl}",
        r"\toprule",
        r"Split & Model & $\Delta F1_{\rm HT}$ & $\mathrm{SE}_{\rm paired}$ & 95\% interval & $\Delta$Lift & 95\% interval \\",
        r" & & (pp) & ($10^{-3}$ pp) & (pp) & & \\",
        r"\midrule",
    ]
    for row in contrasts:
        r = row["statistics"]
        lines.append(
            f"{row['dataset']} & {_model_tex(row['model'])} & "
            f"{100*r['difference']['f1']:.4f} & {1e5*r['sampling_se']['f1']:.2f} & "
            f"{_interval_tex(r['envelope95']['f1'], 100)} & "
            f"{r['difference']['lift']:.3f} & {_interval_tex(r['envelope95']['lift'], digits=3)} \\\\"
        )
    lines.extend([
        r"\bottomrule", r"\end{tabular}",
        (r"\caption{Few-shot minus zero-shot differences in five-run mean metrics. "
        r"F1 differences and endpoints are percentage points; paired linearized SE "
        r"is in $10^{-3}$ percentage points. The SE uses same-edge covariance across "
        r"both prompts and all runs. Conservative 95\% envelopes use simultaneous "
        r"bounds on 30 run--stratum counts and do not exploit pairing. Coverage is "
        r"per comparison, not simultaneous across this table. Endpoints are rounded outwards.}"),
        r"\label{tab:llm_sampling_contrasts}", r"\end{table*}", "",
    ])
    (out / "llm_sampling_contrasts.tex").write_text("\n".join(lines))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inputs", type=Path, default=paths.results() / "analysis/sampling_uncertainty/inputs")
    parser.add_argument("--out", type=Path, default=paths.results() / "analysis/sampling_uncertainty")
    parser.add_argument("--paper-tables", type=Path)
    args = parser.parse_args(argv)
    args.out.mkdir(parents=True, exist_ok=True)
    cells, contrasts, summary_rows, per_seed_rows, contrast_rows = [], [], [], [], []
    source_hashes = {}
    for dataset in ("HI-Small", "LI-Small"):
        for suffix in ("npz", "json"):
            name = f"{dataset}.{suffix}"
            source_hashes[name] = hashlib.sha256((args.inputs / name).read_bytes()).hexdigest()
        matrix = np.load(args.inputs / f"{dataset}.npz", allow_pickle=False)
        metadata = json.loads((args.inputs / f"{dataset}.json").read_text())
        population_sizes = metadata["population_sizes"]
        common = (matrix["labels"], matrix["stratum_ids"], population_sizes)
        predictions = matrix["predictions"]
        models = matrix["models"].astype(str).tolist()
        promptings = matrix["promptings"].astype(str).tolist()
        for j, (model, prompting) in enumerate(zip(models, promptings)):
            result = summarize_cell(predictions[:, j, :], *common)
            key = {"dataset": dataset, "model": model, "prompting": prompting}
            cells.append({**key, "statistics": result})
            row = dict(key)
            for metric in ("p", "r", "f1", "lift"):
                scale = 1 if metric == "lift" else 100
                row[metric] = scale * result["mean"][metric]
                row[metric + "_seed_sd"] = scale * result["seed_sd"][metric]
                row[metric + "_sampling_se"] = scale * result["sampling_se"][metric]
                if metric != "r":
                    row[metric + "_lower"] = scale * result["envelope95"][metric][0]
                    row[metric + "_upper"] = scale * result["envelope95"][metric][1]
            floor = result["predict_all"]["f1"] * 100
            row["predict_all_f1"] = floor
            row["f1_minus_predict_all"] = row["f1"] - floor
            row["f1_lower_minus_predict_all"] = row["f1_lower"] - floor
            row["f1_upper_minus_predict_all"] = row["f1_upper"] - floor
            summary_rows.append(row)
            for seed, seed_result in zip(matrix["seeds"], result["per_seed"]):
                per_seed_rows.append({**key, "seed": int(seed), **seed_result})
        for model in dict.fromkeys(models):
            a = next(j for j in range(len(models)) if models[j] == model and promptings[j] == "ICL-FS")
            b = next(j for j in range(len(models)) if models[j] == model and promptings[j] == "ICL-ZS")
            result = summarize_contrast(predictions[:, a, :], predictions[:, b, :], *common)
            key = {"dataset": dataset, "model": model, "contrast": "ICL-FS minus ICL-ZS"}
            contrasts.append({**key, "statistics": result})
            row = dict(key)
            for metric in ("p", "f1", "lift"):
                scale = 1 if metric == "lift" else 100
                row[metric + "_difference"] = scale * result["difference"][metric]
                row[metric + "_paired_se"] = scale * result["sampling_se"][metric]
                row[metric + "_lower"] = scale * result["envelope95"][metric][0]
                row[metric + "_upper"] = scale * result["envelope95"][metric][1]
            contrast_rows.append(row)
    report = {
        "created_utc": datetime.now(timezone.utc).isoformat(),  # Python 3.10 runtime
        "input_sha256": source_hashes,
        "script_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "module_sha256": hashlib.sha256(
            (Path(__file__).resolve().parent.parent / "amlc/analysis/sampling_uncertainty.py").read_bytes()
        ).hexdigest(),
        "units": "JSON uses fractions for P/R/F1; summary and contrast CSVs use percentages/percentage points; per_seed.csv uses fractions; Lift is dimensionless",
        "scope": "Conditional frozen design and realized allocation; mean of five fixed-run metrics. No future-inference or external-population uncertainty.",
        "intervals": "Equal-tailed hypergeometric inversion with Bonferroni allocation within each cell (15 counts) or contrast (30 counts); not simultaneous across output rows.",
        "cells": cells, "contrasts": contrasts,
    }
    (args.out / "analysis.json").write_text(json.dumps(report, indent=2, allow_nan=False) + "\n")
    pd.DataFrame(summary_rows).to_csv(args.out / "summary.csv", index=False)
    pd.DataFrame(per_seed_rows).to_csv(args.out / "per_seed.csv", index=False)
    pd.DataFrame(contrast_rows).to_csv(args.out / "fs_zs_contrasts.csv", index=False)
    if args.paper_tables:
        write_paper_tables(args.paper_tables, cells, contrasts)
    print(f"Wrote {len(cells)} cells, {len(per_seed_rows)} seed rows, and {len(contrasts)} FS-ZS contrasts to {args.out}")


if __name__ == "__main__":
    main()
